### ISSUE TITLE
Gyp rebuild issue

### ISSUE THREAD

**Issue by jrozestw** [brianc/node-libpq#10]
Hi, 
I experienced an issue when re-running npm install in my project. Please see the log:

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.5.1 install script.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

My node version: 0.10.29, gyp version 0.13.1.

**Comment by SupremeTechnopriest** [comment]
:+1:  Im also seeing this on `node 0.10` `node 0.12` and `iojs 1.6.3`

**Comment by SupremeTechnopriest** [comment]
here is some more detailed output
```bash
> libpq@1.5.1 install /Users/rl/Sites/LumeFX/LumeFX-API/node_modules/pg-native/node_modules/libpq
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/connection.o
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:207:43: error: inline declaration of 'NanNew' follows
      non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: previous definition is
      here
NanNew(v8::Handle<T> h) {
^
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew' follows
      non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: previous definition is
      here
NanNew(v8::Persistent<T> const& p) {
^
2 errors generated.
make: *** [Release/obj.target/addon/src/connection.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/rl/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/Users/rl/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/rl/Sites/LumeFX/LumeFX-API/node_modules/pg-native/node_modules/libpq
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.5.1 install script.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "/Users/rl/.nvm/v0.10.36/bin/node" "/Users/rl/.nvm/v0.10.36/bin/npm" "install"
npm ERR! cwd /Users/rl/Sites/LumeFX/LumeFX-API
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by MCF** [comment]
I'm seeing the same error on the latest version of OSX:
```
$ iojs -v
v1.6.4
$ uname -a
Darwin 14.3.0 Darwin Kernel Version 14.3.0: Mon Mar 23 11:59:05 PDT 2015; root:xnu-2782.20.48~5/RELEASE_X86_64 x86_64
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by pcothenet** [comment]
Same here.

both node-libpq and pg-native are failing at install since the latest OSX update this morning.

```
npm install libpq
|
> libpq@1.5.1 install /Users/pcothenet/Git/madkudu-common/node_modules/libpq
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/connection.o
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:207:43: error: inline declaration of 'NanNew' follows
      non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Handle<T> h);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:210:1: note: previous definition is here
NanNew(v8::Handle<T> h) {
^
In file included from ../src/connection.cc:1:
In file included from ../src/addon.h:5:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:208:43: error: inline declaration of 'NanNew' follows
      non-inline definition
template <typename T> inline v8::Local<T> NanNew(v8::Persistent<T> const& p);
                                          ^
../node_modules/nan/nan_implementation_pre_12_inl.h:216:1: note: previous definition is here
NanNew(v8::Persistent<T> const& p) {
^
2 errors generated.
make: *** [Release/obj.target/addon/src/connection.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/pcothenet/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/Users/pcothenet/.nvm/v0.10.36/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/pcothenet/Git/madkudu-common/node_modules/libpq
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/pcothenet/.nvm/v0.10.36/bin/npm" "install" "libpq"
npm ERR! node v0.10.36
npm ERR! npm  v2.5.0
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.5.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.5.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.
```

node 0.10.36. Same error with 0.12.2

**Comment by MCF** [comment]
The nan dependency is stale.  libpq is requiring 1.5.0 which has the build problem seen above.  The issue was noted here: https://github.com/rvagg/nan/issues/231 and fixed in nan 1.7.0.

**Comment by MCF** [comment]
There is already a pull request to fix this:
https://github.com/brianc/node-libpq/pull/11

**Comment by gregoralbrecht** [comment]
Also seeing this on `node 0.12.2` with `gyp 1.0.3`. I'm on windows though, if that matters at all.

**Comment by brianc** [comment]
This should be fixed now - sorry for the delay. I un-pinned the version of `node-nan` in package.json.

**Comment by brianc** [comment]
This should be fixed now - sorry for the delay. I un-pinned the version of `node-nan` in package.json.

**Comment by shashu10** [comment]
I'm having the same problem with the latest version of npm and node on OSX 10.11.2

snk$ npm install libpq

> libpq@1.8.0 install /Users/snk/Workspace/grapejuice-buzz/node_modules/libpq
> node-gyp rebuild

/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.2.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/snk/Workspace/grapejuice-buzz/node_modules/libpq
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN EPEERINVALID cls-bluebird@1.0.1 requires a peer of continuation-local-storage@~3 but none was installed.
npm WARN EPACKAGEJSON grapejuice_buzz@0.0.1 No description
npm WARN EPACKAGEJSON grapejuice_buzz@0.0.1 No repository field.
npm WARN EPACKAGEJSON grapejuice_buzz@0.0.1 No license field.
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "libpq"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! libpq@1.8.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/snk/Workspace/grapejuice-buzz/npm-debug.log
