### ISSUE TITLE
Failing to install in Win 8

### ISSUE THREAD

**Issue by peek4y** [brianc/node-libpq#15]
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (G:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:
12)
gyp ERR! System Windows_NT 6.2.9200
gyp ERR! command "node" "G:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\sharesliquid\omega.core\node_modules\libpq
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! libpq@1.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the libpq@1.6.1 install script.
npm ERR! This is most likely a problem with the libpq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls libpq
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.2.9200
npm ERR! command "G:\\Program Files\\nodejs\\\\node.exe" "G:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "libpq"
npm ERR! cwd D:\sharesliquid\omega.core
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

**Comment by brianc** [comment]
Did it use to work for you?  Do you have `pg_config` in your path & available to node-gyp?

**Comment by peek4y** [comment]
Yes it was working fine for me. Then it failed in Mac OS X. After the
recent fix on pg-native for Mac OS it started failing in windows

**Comment by brianc** [comment]
I'm pretty sure this commit is the offending one:

https://github.com/brianc/node-libpq/commit/d658d489d0b87c4e2e432fb880d1457e987324f6

Can you look at that gypfile config in there and see if there are any obvious errors? I don't have access to a windows machine. If all else fails I can manually undo the changes to the windows version of the config since it seemed to work just fine previously.

**Comment by brianc** [comment]
@peek4y can you see if this PR fixes your install issue on windows? https://github.com/brianc/node-libpq/pull/20

**Comment by peek4y** [comment]
@brianc  Nope that did not work :( still can't install.

**Comment by brianc** [comment]
Sorry for the dumb question but did you clone this repo & attempt to build the branch containing the PR? I haven't pushed the PR changes to npm yet so installing from NPM is still gonna fail.

**Comment by brianc** [comment]
I'm gonna push that fix to npm right now anyways since it did fix someone's windows issue.

**Comment by brianc** [comment]
`npm install libpq@1.6.4` should have the fix now if you wanna try from npm

**Comment by peek4y** [comment]
Nope, I didn't clone. Will check again now.

**Comment by peek4y** [comment]
YAY! Works perfectly. Thanks @brianc

**Comment by brianc** [comment]
Awesome!  I'm happy it fixed it!! :dancer: 
Thanks so much for testing it - sorry I don't have access to a well configured windows env.

**Comment by peek4y** [comment]
:+1:  No problem, and thanks again.
