### ISSUE TITLE
Newest version fails to install with pg_config installed outside of /usr

### ISSUE THREAD

**Issue by Nopik** [brianc/node-libpq#16]
In case of BOSH installs pg_config is somewhere under /var/vcap/. Previous libpq was working fine, this one stopped to work.

Suggested workaround: check if pg_config is in path first. If not, then look for it.

**Comment by brianc** [comment]
@Nopik - thanks for that.  Does this look like it will fix things for you? 

https://github.com/brianc/node-libpq/pull/17

**Comment by Nopik** [comment]
It looks right.

**Comment by brianc** [comment]
K - I'll merge & bump the version - wanna try after that?

**Comment by brianc** [comment]
@Nopik published libpq@1.6.2 -- it should automatically be picked up next time you try to npm install pg-native

**Comment by Nopik** [comment]
It works now, thanks!
