### ISSUE TITLE
npm install failed with iojs 3.2.0 due to dependence on old nan module.

### ISSUE THREAD

**Issue by Dzenly** [brianc/node-libpq#30]
`node_modules\libpq\node_modules\nan\nan.h(326): error C2995: 'v8::Local<T> Nan::imp::NanEnsureHandleOrPersistent(const v8::Local<T> &)' : function template has already been defined (..\src\connect-async-worker.cc)`

Could you change used nan version ?

I think the same issue will be with iojs 3.0.0 also.
iojs long ago are not in experimental state, and becomes very popular, I think it is worth to make some work for iojs support.

UPDATE: Sorry, just noticed pull request on this issue.

**Comment by brianc** [comment]
No problemo - I merged the PR - thinks working better now with `libpq@1.7.0`?
