### ISSUE TITLE
Node v4.x compatibility

### ISSUE THREAD

**Issue by jmealo** [brianc/node-libpq#32]
Hello, I'm having the following issue happen on Ubuntu 14.04 and OSX 10.9 with the latest Node.

```
Assertion failed: (!(handle->flags & (UV_CLOSING | UV_CLOSED))), function uv_poll_start, file ../deps/uv/src/unix/poll.c, line 90.
```

It was working fine on 0.12.x

I'm doing my best to debug it but it's happening far outside the reach of my code happening deep in the UV/C side. Is anyone else having this issue?

**Comment by abenhamdine** [comment]
Adding to the list: nodejs/node#2798.
Related: #25

**Comment by brianc** [comment]
There were some issues with the version of npm shipping with node v4.0 that are now fixed.

This module builds & runs fine on node 4.0:

https://travis-ci.org/brianc/node-libpq

@abenhamdine please remove it from the list.  Thanks! :smile:
