### ISSUE TITLE
getting error as of 1.8.6

### ISSUE THREAD

**Issue by scamden** [brianc/node-libpq#53]
``` libpq@1.8.6 install /Users/scamden/creditiq/api/functions/services/broadcast/node_modules/libpq
> node-gyp rebuild

  CXX(target) Release/obj.target/addon/src/connection.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)```

**Comment by scamden** [comment]
@brianc not sure who to ping here but this is a pretty major problem in a patch bump, so it's breaking all over the place for me, and probably a lot of other mac users

**Comment by elhoyos** [comment]
I have the same error when using node@4.4.7, however when using node@6.9.5 it builds ok for me.

I recently installed XCode 8.3 with its Command Line Tools in 10.12.3. Can't tell if this was the cause of the problem.

#49 seems highly related.

**Comment by brianc** [comment]
Hmm - it's building and passing in travis @ `1.4.x` and `1.6.x` - I'm 100% open to pull requests to fix build issues related to OS X + xcode + `1.4.x` node and would greatly appreciate them!  Feel free to ping me if you figure out what's wrong!

**Comment by scamden** [comment]
verified the newest patch installs properly. thanks for publishin so quickly.
