### ISSUE TITLE
[RESOLVED] Node 12 support

### ISSUE THREAD

**Issue by darkgl0w** [brianc/node-libpq#68]
Hello,

I open this issue in order to track `nan` support for Node 12 here : https://github.com/nodejs/nan/issues/849.

Currently the PR I submitted here https://github.com/brianc/node-libpq/pull/67 is building successfully but segfault on tests inside Travis Node 12 environment. (so far I have no problem on my local machine).

For reference here is the report: https://travis-ci.org/brianc/node-libpq/jobs/531071467

NB: Currently the package compile successfully and pass all tests on my Node 12 dev environment (copy pasted the results here: https://pastebin.com/HWWcQD2v).

I will report back any update and progress on this. ^^

**Comment by sandyplace** [comment]
Just checking has any movement happened on this issue yet? According to nodejs/nan it is no longer an open issue over there. Is it a matter of updating the package dependencies now?

**Comment by darkgl0w** [comment]
@sandyplace > We are still working on this PR https://github.com/brianc/node-libpq/pull/67
