### ISSUE TITLE
Getting a mem leak on "libpq:connection:emit'

### ISSUE THREAD

**Issue by bencmbrook** [brianc/node-libpq#78]
Is there any way `node-libpq` has a memory leak on this event?

https://github.com/brianc/node-libpq/blob/4848a6f91b5ec48e580b4d91156c659746a291e8/src/connection.cc#L804

If this is user error, can you provide any guidance on what type of (mis)usage may result in an ever-growing number of "libpq:connection:emit" asynchronous resources?

**Comment by ruimarinho** [comment]
@bencmbrook does https://github.com/brianc/node-libpq/pull/77/files fix your issue?

**Comment by bencmbrook** [comment]
@ruimarinho can't say, sorry -- we've migrated off. Feel free to close this out since I can't verify the bugfix
