### ISSUE TITLE
Is Node 14 supported?

### ISSUE THREAD

**Issue by gagyibenedek** [brianc/node-libpq#83]
Based on the .travis.yml file it's not:
`node_js:
  - "12"
  - "10"
  - "8"
  - "6"
  - "4"`
  
  Is this correct?
  Does anyone have any pointers where I should look, if I was planning to create a PR that would introduce Node 14 compatibility?

**Comment by cclauss** [comment]
Can this be closed?  It seems to run fine on GitHub Actions.
